# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first


Card.create(rank: "clubs", card_type: "number", color: "black", value: 2, img: "", deck_id: 1)
Card.create(rank: "clubs", card_type: "number", color: "black", value: 3, img: "", deck_id: 1)
Card.create(rank: "clubs", card_type: "number", color: "black", value: 4, img: "", deck_id: 1)
Card.create(rank: "clubs", card_type: "number", color: "black", value: 5, img: "", deck_id: 1)
Card.create(rank: "clubs", card_type: "number", color: "black", value: 6, img: "", deck_id: 1)
Card.create(rank: "clubs", card_type: "number", color: "black", value: 7, img: "", deck_id: 1)
Card.create(rank: "clubs", card_type: "number", color: "black", value: 8, img: "", deck_id: 1)
Card.create(rank: "clubs", card_type: "number", color: "black", value: 9, img: "", deck_id: 1)
Card.create(rank: "clubs", card_type: "number", color: "black", value: 10, img: "", deck_id: 1)
Card.create(rank: "clubs", card_type: "Jack", color: "black", value: 10, img: "", deck_id: 1)
Card.create(rank: "clubs", card_type: "King", color: "black", value: 10, img: "", deck_id: 1)
Card.create(rank: "clubs", card_type: "Queen", color: "black", value: 10, img: "", deck_id: 1)
Card.create(rank: "clubs", card_type: "Ace", color: "black", value: 11, img: "", deck_id: 1)

Card.create(rank: "spades", card_type: "number", color: "black", value: 2, img: "", deck_id: 1)
Card.create(rank: "spades", card_type: "number", color: "black", value: 3, img: "", deck_id: 1)
Card.create(rank: "spades", card_type: "number", color: "black", value: 4, img: "", deck_id: 1)
Card.create(rank: "spades", card_type: "number", color: "black", value: 5, img: "", deck_id: 1)
Card.create(rank: "spades", card_type: "number", color: "black", value: 6, img: "", deck_id: 1)
Card.create(rank: "spades", card_type: "number", color: "black", value: 7, img: "", deck_id: 1)
Card.create(rank: "spades", card_type: "number", color: "black", value: 8, img: "", deck_id: 1)
Card.create(rank: "spades", card_type: "number", color: "black", value: 9, img: "", deck_id: 1)
Card.create(rank: "spades", card_type: "number", color: "black", value: 10, img: "", deck_id: 1)
Card.create(rank: "spades", card_type: "Jack", color: "black", value: 10, img: "", deck_id: 1)
Card.create(rank: "spades", card_type: "King", color: "black", value: 10, img: "", deck_id: 1)
Card.create(rank: "spades", card_type: "Queen", color: "black", value: 10, img: "", deck_id: 1)
Card.create(rank: "spades", card_type: "Ace", color: "black", value: 11, img: "", deck_id: 1)

Card.create(rank: "diamonds", card_type: "number", color: "red", value: 2, img: "", deck_id: 1)
Card.create(rank: "diamonds", card_type: "number", color: "red", value: 3, img: "", deck_id: 1)
Card.create(rank: "diamonds", card_type: "number", color: "red", value: 4, img: "", deck_id: 1)
Card.create(rank: "diamonds", card_type: "number", color: "red", value: 5, img: "", deck_id: 1)
Card.create(rank: "diamonds", card_type: "number", color: "red", value: 6, img: "", deck_id: 1)
Card.create(rank: "diamonds", card_type: "number", color: "red", value: 7, img: "", deck_id: 1)
Card.create(rank: "diamonds", card_type: "number", color: "red", value: 8, img: "", deck_id: 1)
Card.create(rank: "diamonds", card_type: "number", color: "red", value: 9, img: "", deck_id: 1)
Card.create(rank: "diamonds", card_type: "number", color: "red", value: 10, img: "", deck_id: 1)
Card.create(rank: "diamonds", card_type: "Jack", color: "red", value: 10, img: "", deck_id: 1)
Card.create(rank: "diamonds", card_type: "King", color: "red", value: 10, img: "", deck_id: 1)
Card.create(rank: "diamonds", card_type: "Queen", color: "red", value: 10, img: "", deck_id: 1)
Card.create(rank: "diamonds", card_type: "Ace", color: "red", value: 11, img: "", deck_id: 1)

Card.create(rank: "hearts", card_type: "number", color: "red", value: 2, img: "", deck_id: 1)
Card.create(rank: "hearts", card_type: "number", color: "red", value: 3, img: "", deck_id: 1)
Card.create(rank: "hearts", card_type: "number", color: "red", value: 4, img: "", deck_id: 1)
Card.create(rank: "hearts", card_type: "number", color: "red", value: 5, img: "", deck_id: 1)
Card.create(rank: "hearts", card_type: "number", color: "red", value: 6, img: "", deck_id: 1)
Card.create(rank: "hearts", card_type: "number", color: "red", value: 7, img: "", deck_id: 1)
Card.create(rank: "hearts", card_type: "number", color: "red", value: 8, img: "", deck_id: 1)
Card.create(rank: "hearts", card_type: "number", color: "red", value: 9, img: "", deck_id: 1)
Card.create(rank: "hearts", card_type: "number", color: "red", value: 10, img: "", deck_id: 1)
Card.create(rank: "hearts", card_type: "Jack", color: "red", value: 10, img: "", deck_id: 1)
Card.create(rank: "hearts", card_type: "King", color: "red", value: 10, img: "", deck_id: 1)
Card.create(rank: "hearts", card_type: "Queen", color: "red", value: 10, img: "", deck_id: 1)
Card.create(rank: "hearts", card_type: "Ace", color: "red", value: 11, img: "", deck_id: 1)
Table.create()
Deck.create(table_id: 1) 